name: '이슈 생성'
description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: []
title: '이슈 이름을 작성해주세요'
body:
  - type: input
    id: description
    attributes:
      label: '📄 Describe - 무엇에 대한 이슈인지 설명을 적어주세요.'
    validations:
      required: false

  - type: input
    id: tasks
    attributes:
      label: '✅ Tasks - 해야 할 일들을 체크박스 형식으로 작성해주세요. 예: [ ] 기능 구현'
    validations:
      required: false

  - type: input
    id: ref
    attributes:
      label: '📋 Ref - 참고할 만한 링크나 문서를 남겨주세요.'
    validations:
      required: false
