name: Close Jira issue

on:
  issues:
    types: [closed]

jobs:
  close-issue:
    name: Close Jira issue
    runs-on: ubuntu-latest

    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Extract Jira issue key from GitHub issue
        id: extract-key
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | grep -oE '[A-Z]+-[0-9]+' || true)

          JIRA_KEY=$(echo "$ISSUE_TITLE $ISSUE_BODY $ISSUE_LABELS" | grep -oE '[A-Z]+-[0-9]+' | head -n1 || true)

          if [ -z "$JIRA_KEY" ]; then
            echo "❌ No Jira issue key found in title, body, or labels."
            exit 1
          fi

          echo "✅ Found Jira key: $JIRA_KEY"
          echo "JIRA_KEY=$JIRA_KEY" >> $GITHUB_ENV

      - name: Transition Jira issue to Done
        if: env.JIRA_KEY != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.JIRA_KEY }}
          transition: Mark as Done  # ← Jira에서 실제 설정한 transition 이름
